
const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})

const outputFile = './swagger_output.json'
const endpointsFiles = ['./app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "API de candidatos",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        Candidato: {
            $cpf: "72660766096",
            $rg: "85722332020",
            $nome: "Cinthya Dayane Morales",
            $cargo: "Dev",
            $nascimento: "09/09/1990",
            $estado_civil: "Casado",
            $sexo: "masculino",
            $email: "teste@teste.com",
            $tem_cnh: true,
            $tem_veiculo: true,
            $cep: "803121090",
            $bairro: "Rebouças",
            $cidade: "Curitiba",
            $endereco: "Avenida Presidente Getúlio Vargas",
            $numero_casa: "212",
            $celular: "041991026666",
            $telefone: "041997075644"
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc)
